[tools]
node = { version = "latest", postinstall = "npm install -g rtlcss" }
python = "3.12"

[settings]
experimental = true

[env]
_.path = ["{{config_root}}"]
COMPOSE_FILE = "{{config_root}}/services/compose.yml"

[hooks]
postinstall = "pip install -e {{config_root}} -q"
