import json
from pathlib import Path

from ow.config import BranchSpec, Config, WorkspaceConfig
from ow.workspace import (
    make_mise_toml,
    make_odools_toml,
    make_odoorc,
    make_pyrightconfig,
    make_requirements_dev,
    make_vscode_settings,
    make_zed_settings,
    make_vscode_launch,
    make_zed_debug,
)


def make_config(
    workspaces=None,
    root_dir=None,
    odoorc=None,
    remotes=None,
) -> Config:
    return Config(
        odoorc=odoorc or {"http_port": 8069, "db_host": "localhost", "db_port": 5432},
        remotes=remotes or {},
        workspaces=workspaces or [],
        root_dir=root_dir or Path("/root"),
    )


def community_only() -> WorkspaceConfig:
    return WorkspaceConfig(
        name="test",
        repos={"community": BranchSpec("origin/master")},
    )


def community_enterprise() -> WorkspaceConfig:
    return WorkspaceConfig(
        name="test",
        repos={
            "community": BranchSpec("origin/master"),
            "enterprise": BranchSpec("origin/master", "master-test"),
        },
    )


def full_workspace() -> WorkspaceConfig:
    return WorkspaceConfig(
        name="test",
        repos={
            "community": BranchSpec("origin/master"),
            "enterprise": BranchSpec("origin/master", "master-test"),
            "brboi-addons": BranchSpec("origin/main"),
        },
    )


# ---------------------------------------------------------------------------
# make_odoorc
# ---------------------------------------------------------------------------

def test_odoorc_community_only():
    ws = community_only()
    config = make_config()
    result = make_odoorc(ws, config)

    assert "[options]" in result
    assert "http_port = 8069" in result
    assert "db_host = localhost" in result
    assert "# following is autogenerated" in result
    assert "community/addons" in result
    assert "community/odoo/addons" in result
    assert "db_name = test" in result
    assert "dbfilter = ^test$" in result


def test_odoorc_addons_path_enterprise_before_community():
    ws = community_enterprise()
    config = make_config(root_dir=Path("/root"))
    result = make_odoorc(ws, config)

    lines = result.split("\n")
    addons_line = next(l for l in lines if l.startswith("addons_path"))
    paths = addons_line.split("=", 1)[1].strip().split(",")

    assert "enterprise" in paths[0]
    assert "community/addons" in paths[1]
    assert "community/odoo/addons" in paths[2]


def test_odoorc_full_workspace_addons_order():
    ws = full_workspace()
    config = make_config(root_dir=Path("/root"))
    result = make_odoorc(ws, config)

    lines = result.split("\n")
    addons_line = next(l for l in lines if l.startswith("addons_path"))
    paths = addons_line.split("=", 1)[1].strip().split(",")

    # enterprise and brboi-addons first, then community paths
    non_comm = [p for p in paths if "community/addons" not in p and "community/odoo/addons" not in p]
    comm = [p for p in paths if "community/addons" in p or "community/odoo/addons" in p]
    assert len(non_comm) == 2
    assert len(comm) == 2


def test_odoorc_workspace_overrides_global():
    ws = WorkspaceConfig(
        name="test",
        repos={"community": BranchSpec("origin/master")},
        odoorc={"http_port": 8070},
    )
    config = make_config()
    result = make_odoorc(ws, config)

    assert "http_port = 8070" in result
    assert "http_port = 8069" not in result  # global was overridden


def test_odoorc_no_quotes_on_string_values():
    ws = community_only()
    config = make_config()
    result = make_odoorc(ws, config)

    # INI values must not be quoted
    assert 'db_host = "localhost"' not in result
    assert "db_host = localhost" in result


def test_odoorc_absolute_addons_paths():
    ws = community_enterprise()
    config = make_config(root_dir=Path("/my/root"))
    result = make_odoorc(ws, config)

    assert "/my/root/workspaces/test/enterprise" in result
    assert "/my/root/workspaces/test/community/addons" in result


# ---------------------------------------------------------------------------
# make_odools_toml
# ---------------------------------------------------------------------------

def test_odools_community_only():
    ws = community_only()
    result = make_odools_toml(ws)

    assert "[[config]]" in result
    assert '[Odoo Workspace] test' in result
    assert 'python_path = ".venv/bin/python"' in result
    assert 'odoo_path = "./community"' in result
    assert "./community/addons" in result
    assert "./community/odoo/addons" in result
    # No non-community repos
    assert "./enterprise" not in result


def test_odools_community_enterprise_order():
    ws = community_enterprise()
    result = make_odools_toml(ws)

    assert "./enterprise" in result
    ent_idx = result.index("./enterprise")
    com_idx = result.index("./community/addons")
    assert ent_idx < com_idx


def test_odools_full_workspace():
    ws = full_workspace()
    result = make_odools_toml(ws)

    assert "./enterprise" in result
    assert "./brboi-addons" in result
    assert "./community/addons" in result
    assert "./community/odoo/addons" in result


# ---------------------------------------------------------------------------
# make_mise_toml
# ---------------------------------------------------------------------------

def test_mise_toml_structure():
    result = make_mise_toml()

    assert "[tools]" in result
    assert "python" in result
    assert "[hooks]" in result
    assert "community/requirements.txt" in result
    assert "[env]" in result
    assert ".venv" in result


# ---------------------------------------------------------------------------
# make_requirements_dev
# ---------------------------------------------------------------------------

def test_requirements_dev():
    result = make_requirements_dev()
    assert "inotify" in result


# ---------------------------------------------------------------------------
# make_vscode_settings
# ---------------------------------------------------------------------------

def test_vscode_settings():
    ws = community_enterprise()
    result = make_vscode_settings(ws)

    assert "[Odoo Workspace] test" in result


# ---------------------------------------------------------------------------
# make_vscode_launch
# ---------------------------------------------------------------------------

def test_vscode_launch():
    result = make_vscode_launch()

    assert "debugpy" in result
    assert "${workspaceFolder}/community" in result
    assert "odoo-bin" in result
    assert "odoorc" in result


# ---------------------------------------------------------------------------
# make_zed_settings
# ---------------------------------------------------------------------------

def test_zed_settings_community_enterprise():
    ws = community_enterprise()
    result = make_zed_settings(ws)

    assert "community/**" in result
    assert "enterprise/**" in result
    assert "[Odoo Workspace] test" in result
    assert '"mise.toml"' in result
    assert '"odools.toml"' in result
    assert '"pyrightconfig.json"' in result
    assert '"**/.venv"' in result


def test_zed_settings_full_workspace():
    ws = full_workspace()
    result = make_zed_settings(ws)

    assert "community/**" in result
    assert "enterprise/**" in result
    assert "brboi-addons/**" in result
    assert '"mise.toml"' in result
    assert '"odools.toml"' in result
    assert '"pyrightconfig.json"' in result
    assert '"**/.venv"' in result


# ---------------------------------------------------------------------------
# make_pyrightconfig
# ---------------------------------------------------------------------------

def test_pyrightconfig():
    result = make_pyrightconfig()
    data = json.loads(result)

    assert data["venvPath"] == "."
    assert data["venv"] == ".venv"
    assert data["pythonVersion"] == "3.12"
    assert "./community" in data["extraPaths"]
    assert data["typeCheckingMode"] == "off"


# ---------------------------------------------------------------------------
# make_zed_debug
# ---------------------------------------------------------------------------

def test_zed_debug():
    result = make_zed_debug()

    assert "Debugpy" in result
    assert "${ZED_WORKTREE_ROOT}/community" in result
    assert "odoo-bin" in result
    assert "${ZED_WORKTREE_ROOT}/.venv/bin/python" in result
    assert "odoorc" in result
