import json
from pathlib import Path

import pytest

from ow.config import BranchSpec, Config, WorkspaceConfig
from ow.workspace import (
    find_addon_paths,
    is_odoo_main_repo,
    make_mise_toml,
    make_odools_toml,
    make_odoorc,
    make_pyrightconfig,
    make_requirements_dev,
    make_vscode_settings,
    make_zed_settings,
    make_vscode_launch,
    make_zed_debug,
)


def make_config(
    workspaces=None,
    root_dir=None,
    odoorc=None,
    remotes=None,
) -> Config:
    return Config(
        odoorc=odoorc or {"http_port": 8069, "db_host": "localhost", "db_port": 5432},
        remotes=remotes or {},
        workspaces=workspaces or [],
        root_dir=root_dir or Path("/root"),
    )


# ---------------------------------------------------------------------------
# Filesystem fixtures helpers
# ---------------------------------------------------------------------------

def setup_odoo_main_repo(ws_dir: Path, alias: str = "community") -> Path:
    repo = ws_dir / alias
    repo.mkdir(parents=True, exist_ok=True)
    (repo / "odoo-bin").touch()
    (repo / "addons" / "sale").mkdir(parents=True)
    (repo / "addons" / "sale" / "__manifest__.py").touch()
    (repo / "odoo" / "addons" / "base").mkdir(parents=True)
    (repo / "odoo" / "addons" / "base" / "__manifest__.py").touch()
    return repo


def setup_flat_repo(ws_dir: Path, alias: str) -> Path:
    """Repo where the root is directly an addons_path."""
    repo = ws_dir / alias
    (repo / "account").mkdir(parents=True)
    (repo / "account" / "__manifest__.py").touch()
    (repo / "sale").mkdir(parents=True)
    (repo / "sale" / "__manifest__.py").touch()
    return repo


def setup_categorized_repo(ws_dir: Path, alias: str) -> Path:
    """Repo whose immediate subdirs are each addons_paths (one level of nesting)."""
    repo = ws_dir / alias
    (repo / "telephony" / "phone_validation").mkdir(parents=True)
    (repo / "telephony" / "phone_validation" / "__manifest__.py").touch()
    (repo / "messaging" / "sms_gateway").mkdir(parents=True)
    (repo / "messaging" / "sms_gateway" / "__manifest__.py").touch()
    return repo


def make_ws_config(name: str, aliases: list[str]) -> WorkspaceConfig:
    return WorkspaceConfig(
        name=name,
        repos={alias: BranchSpec("origin/master") for alias in aliases},
    )


# ---------------------------------------------------------------------------
# find_addon_paths
# ---------------------------------------------------------------------------

def test_find_addon_paths_on_file(tmp_path):
    f = tmp_path / "somefile.txt"
    f.touch()
    assert find_addon_paths(f) == []


def test_find_addon_paths_nonexistent(tmp_path):
    assert find_addon_paths(tmp_path / "nonexistent") == []


def test_find_addon_paths_empty_dir(tmp_path):
    d = tmp_path / "empty"
    d.mkdir()
    assert find_addon_paths(d) == []


def test_find_addon_paths_flat_repo(tmp_path):
    repo = setup_flat_repo(tmp_path, "myaddon")
    assert find_addon_paths(repo) == [repo]


def test_find_addon_paths_categorized_repo(tmp_path):
    repo = setup_categorized_repo(tmp_path, "myaddon")
    result = find_addon_paths(repo)
    assert result == sorted([repo / "messaging", repo / "telephony"])


def test_find_addon_paths_mixed_depths(tmp_path):
    repo = tmp_path / "repo"
    # helpers/utils/__manifest__.py  → helpers is addons_path
    (repo / "helpers" / "utils").mkdir(parents=True)
    (repo / "helpers" / "utils" / "__manifest__.py").touch()
    # categories/crm/sale_crm/__manifest__.py  → crm is addons_path
    (repo / "categories" / "crm" / "sale_crm").mkdir(parents=True)
    (repo / "categories" / "crm" / "sale_crm" / "__manifest__.py").touch()
    # external/vendor/payments/stripe/__manifest__.py → payments is addons_path
    (repo / "external" / "vendor" / "payments" / "stripe").mkdir(parents=True)
    (repo / "external" / "vendor" / "payments" / "stripe" / "__manifest__.py").touch()

    result = find_addon_paths(repo)
    assert result == sorted([
        repo / "categories" / "crm",
        repo / "external" / "vendor" / "payments",
        repo / "helpers",
    ])


# ---------------------------------------------------------------------------
# make_odoorc
# ---------------------------------------------------------------------------

def test_odoorc_community_only(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    ws = make_ws_config("test", ["community"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    assert "[options]" in result
    assert "http_port = 8069" in result
    assert "db_host = localhost" in result
    assert "# following is autogenerated" in result
    assert "community/addons" in result
    assert "community/odoo/addons" in result
    assert "db_name = test" in result
    assert "dbfilter = ^test$" in result


def test_odoorc_addons_path_enterprise_before_community(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_flat_repo(ws_dir, "enterprise")
    ws = make_ws_config("test", ["community", "enterprise"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    lines = result.split("\n")
    addons_line = next(l for l in lines if l.startswith("addons_path"))
    paths = addons_line.split("=", 1)[1].strip().split(",")

    assert "enterprise" in paths[0]
    assert "community/addons" in paths[1]
    assert "community/odoo/addons" in paths[2]


def test_odoorc_full_workspace_addons_order(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_flat_repo(ws_dir, "enterprise")
    setup_flat_repo(ws_dir, "brboi-addons")
    ws = make_ws_config("test", ["community", "enterprise", "brboi-addons"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    lines = result.split("\n")
    addons_line = next(l for l in lines if l.startswith("addons_path"))
    paths = addons_line.split("=", 1)[1].strip().split(",")

    non_comm = [p for p in paths if "community/addons" not in p and "community/odoo/addons" not in p]
    comm = [p for p in paths if "community/addons" in p or "community/odoo/addons" in p]
    assert len(non_comm) == 2
    assert len(comm) == 2


def test_odoorc_workspace_overrides_global(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    ws = WorkspaceConfig(
        name="test",
        repos={"community": BranchSpec("origin/master")},
        odoorc={"http_port": 8070},
    )
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    assert "http_port = 8070" in result
    assert "http_port = 8069" not in result


def test_odoorc_no_quotes_on_string_values(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    ws = make_ws_config("test", ["community"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    assert 'db_host = "localhost"' not in result
    assert "db_host = localhost" in result


def test_odoorc_absolute_addons_paths(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_flat_repo(ws_dir, "enterprise")
    ws = make_ws_config("test", ["community", "enterprise"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    assert str(ws_dir / "enterprise") in result
    assert str(ws_dir / "community" / "addons") in result


def test_odoorc_categorized_repo(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_categorized_repo(ws_dir, "partner-addons")
    ws = make_ws_config("test", ["community", "partner-addons"])
    config = make_config(root_dir=tmp_path)
    result = make_odoorc(ws, config)

    lines = result.split("\n")
    addons_line = next(l for l in lines if l.startswith("addons_path"))
    paths = addons_line.split("=", 1)[1].strip().split(",")

    # Both sub-paths of partner-addons should appear before community
    assert any("partner-addons/messaging" in p or "partner-addons/telephony" in p for p in paths)
    comm_idx = next(i for i, p in enumerate(paths) if "community/addons" in p)
    non_comm = [p for p in paths[:comm_idx] if "partner-addons" in p]
    assert len(non_comm) == 2


# ---------------------------------------------------------------------------
# make_odools_toml
# ---------------------------------------------------------------------------

def test_odools_community_only(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    ws = make_ws_config("test", ["community"])
    result = make_odools_toml(ws, ws_dir)

    assert "[[config]]" in result
    assert "[Odoo Workspace] test" in result
    assert 'python_path = ".venv/bin/python"' in result
    assert 'odoo_path = "./community"' in result
    assert "./community/addons" in result
    assert "./community/odoo/addons" in result
    assert "./enterprise" not in result


def test_odools_community_enterprise_order(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_flat_repo(ws_dir, "enterprise")
    ws = make_ws_config("test", ["community", "enterprise"])
    result = make_odools_toml(ws, ws_dir)

    assert "./enterprise" in result
    ent_idx = result.index("./enterprise")
    com_idx = result.index("./community/addons")
    assert ent_idx < com_idx


def test_odools_full_workspace(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_flat_repo(ws_dir, "enterprise")
    setup_flat_repo(ws_dir, "brboi-addons")
    ws = make_ws_config("test", ["community", "enterprise", "brboi-addons"])
    result = make_odools_toml(ws, ws_dir)

    assert "./enterprise" in result
    assert "./brboi-addons" in result
    assert "./community/addons" in result
    assert "./community/odoo/addons" in result


def test_odools_categorized_repo(tmp_path):
    ws_dir = tmp_path / "workspaces" / "test"
    setup_odoo_main_repo(ws_dir, "community")
    setup_categorized_repo(ws_dir, "partner-addons")
    ws = make_ws_config("test", ["community", "partner-addons"])
    result = make_odools_toml(ws, ws_dir)

    assert "./partner-addons/messaging" in result
    assert "./partner-addons/telephony" in result
    assert "./community/addons" in result
    # categorized paths before community
    msg_idx = result.index("./partner-addons/messaging")
    com_idx = result.index("./community/addons")
    assert msg_idx < com_idx


# ---------------------------------------------------------------------------
# make_mise_toml
# ---------------------------------------------------------------------------

def test_mise_toml_structure():
    result = make_mise_toml()

    assert "[tools]" in result
    assert "python" in result
    assert "[hooks]" in result
    assert "community/requirements.txt" in result
    assert "[env]" in result
    assert ".venv" in result


# ---------------------------------------------------------------------------
# make_requirements_dev
# ---------------------------------------------------------------------------

def test_requirements_dev():
    result = make_requirements_dev()
    assert "inotify" in result


# ---------------------------------------------------------------------------
# make_vscode_settings
# ---------------------------------------------------------------------------

def test_vscode_settings():
    ws = WorkspaceConfig(
        name="test",
        repos={
            "community": BranchSpec("origin/master"),
            "enterprise": BranchSpec("origin/master", "master-test"),
        },
    )
    result = make_vscode_settings(ws)

    assert "[Odoo Workspace] test" in result


# ---------------------------------------------------------------------------
# make_vscode_launch
# ---------------------------------------------------------------------------

def test_vscode_launch():
    result = make_vscode_launch()

    assert "debugpy" in result
    assert "${workspaceFolder}/community" in result
    assert "odoo-bin" in result
    assert "odoorc" in result


# ---------------------------------------------------------------------------
# make_zed_settings
# ---------------------------------------------------------------------------

def test_zed_settings_community_enterprise():
    ws = WorkspaceConfig(
        name="test",
        repos={
            "community": BranchSpec("origin/master"),
            "enterprise": BranchSpec("origin/master", "master-test"),
        },
    )
    result = make_zed_settings(ws)

    assert "community/**" in result
    assert "enterprise/**" in result
    assert "[Odoo Workspace] test" in result
    assert '"mise.toml"' in result
    assert '"odools.toml"' in result
    assert '"pyrightconfig.json"' in result
    assert '"**/.venv"' in result


def test_zed_settings_full_workspace():
    ws = WorkspaceConfig(
        name="test",
        repos={
            "community": BranchSpec("origin/master"),
            "enterprise": BranchSpec("origin/master", "master-test"),
            "brboi-addons": BranchSpec("origin/main"),
        },
    )
    result = make_zed_settings(ws)

    assert "community/**" in result
    assert "enterprise/**" in result
    assert "brboi-addons/**" in result
    assert '"mise.toml"' in result
    assert '"odools.toml"' in result
    assert '"pyrightconfig.json"' in result
    assert '"**/.venv"' in result


# ---------------------------------------------------------------------------
# make_pyrightconfig
# ---------------------------------------------------------------------------

def test_pyrightconfig():
    result = make_pyrightconfig()
    data = json.loads(result)

    assert data["venvPath"] == "."
    assert data["venv"] == ".venv"
    assert data["pythonVersion"] == "3.12"
    assert "./community" in data["extraPaths"]
    assert data["typeCheckingMode"] == "off"


# ---------------------------------------------------------------------------
# make_zed_debug
# ---------------------------------------------------------------------------

def test_zed_debug():
    result = make_zed_debug()

    assert "Debugpy" in result
    assert "${ZED_WORKTREE_ROOT}/community" in result
    assert "odoo-bin" in result
    assert "${ZED_WORKTREE_ROOT}/.venv/bin/python" in result
    assert "odoorc" in result
