from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from shutil import rmtree

from ow.config import (
    BranchSpec,
    Config,
    WorkspaceConfig,
    archive_workspace,
    format_workspace,
    parse_branch_spec,
    update_config_workspaces,
)
from ow.git import (
    create_worktree,
    ensure_bare_repo,
    get_rev_list_count,
    get_upstream,
    get_worktree_head,
    parallel_fetch,
    remove_worktree,
    resolve_spec,
    resolve_spec_local,
    worktree_exists,
)


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

def make_odoorc(ws: WorkspaceConfig, config: Config) -> str:
    merged = dict(config.odoorc)
    merged.update(ws.odoorc)

    ws_dir = config.root_dir / "workspaces" / ws.name

    lines = ["[options]"]
    for k, v in merged.items():
        lines.append(f"{k} = {v}")

    lines.append("")
    lines.append("# following is autogenerated")

    non_community = [alias for alias in ws.repos if alias != "community"]
    addons = [str(ws_dir / alias) for alias in non_community]
    addons += [str(ws_dir / "community" / "addons"), str(ws_dir / "community" / "odoo" / "addons")]
    lines.append(f"addons_path = {','.join(addons)}")
    lines.append(f"db_name = {ws.name}")
    lines.append(f"dbfilter = ^{ws.name}$")

    return "\n".join(lines) + "\n"


def make_odools_toml(ws: WorkspaceConfig) -> str:
    non_community = [alias for alias in ws.repos if alias != "community"]
    path_items = [f'    "./{alias}"' for alias in non_community]
    path_items += ['    "./community/addons"', '    "./community/odoo/addons"']
    paths_str = ",\n".join(path_items)

    return f"""\
[[config]]
name = "[Odoo Workspace] {ws.name}"
python_path = ".venv/bin/python"
odoo_path = "./community"
addons_paths = [
{paths_str},
]
"""


def make_mise_toml() -> str:
    return """\
[tools]
python = "3.12"

[hooks]
postinstall = "pip install -r community/requirements.txt -r requirements-dev.txt"

[env]
_.python.venv = { path = ".venv", create = true }
_.path = ["{{config_root}}/community"]
"""


def make_requirements_dev() -> str:
    return "inotify\n"


def make_vscode_settings(ws: WorkspaceConfig) -> str:
    return f"""\
{{
  "Odoo.selectedProfile": "[Odoo Workspace] {ws.name}",
}}
"""


def make_vscode_launch() -> str:
    return """\
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Run Instance With Debug",
      "type": "debugpy",
      "request": "launch",
      "cwd": "${workspaceFolder}/community",
      "program": "odoo-bin",
      "justMyCode": false,
      "args": [
        "--config=${workspaceFolder}/odoorc",
        "--dev=all",
      ],
      "env": {
        "PYTHON_PATH": "${workspaceFolder}/community"
      },
    }
  ]
}
"""


def make_zed_settings(ws: WorkspaceConfig) -> str:
    repo_inclusions = ", ".join(f'"{alias}/**"' for alias in ws.repos)
    exclusions = (
        '"**/.git", "**/.svn", "**/.hg", "**/.jj", "**/CVS", "**/.DS_Store", '
        '"**/Thumbs.db", "**/.classpath", "**/.settings", "**/*.po", "**/*.pot", '
        '"**/node_modules", "**/.venv"'
    )
    return f"""\
{{
  "file_scan_inclusions": [{repo_inclusions}, "mise.toml", "odools.toml", "pyrightconfig.json"],
  "file_scan_exclusions": [{exclusions}],
  "lsp": {{
    "odoo": {{
      "settings": {{
        "Odoo.selectedProfile": "[Odoo Workspace] {ws.name}",
      }},
    }},
  }},
}}
"""


def make_zed_debug() -> str:
    return """\
// Project-local debug tasks
//
// For more documentation on how to configure debug tasks,
// see: https://zed.dev/docs/debugger
[
  {
    "label": "Run Instance With Debug",
    "adapter": "Debugpy",
    "request": "launch",
    "console": "integratedTerminal",
    "cwd": "${ZED_WORKTREE_ROOT}/community",
    "program": "odoo-bin",
    "justMyCode": false,
    "args": ["--config=${ZED_WORKTREE_ROOT}/odoorc", "--dev=all"],
    "python": "${ZED_WORKTREE_ROOT}/.venv/bin/python",
    "env": {
      "PYTHONPATH": "${ZED_WORKTREE_ROOT}/community",
    },
  },
]
"""


def make_pyrightconfig() -> str:
    return """\
{
  "venvPath": ".",
  "venv": ".venv",
  "pythonVersion": "3.12",
  "extraPaths": ["./community"],
  "reportArgumentType": "none",
  "reportAttributeAccessIssue": "none",
  "reportMissingImports": "none",
  "reportMissingModuleSource": "none",
  "reportPrivateLocalImportUsage": "none",
  "typeCheckingMode": "off"
}
"""


# ---------------------------------------------------------------------------
# Status helpers
# ---------------------------------------------------------------------------

def _parse_github_org_repo(url: str) -> str | None:
    if url.startswith("git@github.com:"):
        path = url[len("git@github.com:"):]
        return path.removesuffix(".git")
    if "github.com/" in url:
        path = url.split("github.com/", 1)[1]
        return path.removesuffix(".git")
    return None


def _osc8(url: str, text: str) -> str:
    return f"\x1b]8;;{url}\x1b\\{text}\x1b]8;;\x1b\\"


def _c(text: str, *codes: int) -> str:
    prefix = "".join(f"\x1b[{code}m" for code in codes)
    return f"{prefix}{text}\x1b[0m"


def _counts(behind: int, ahead: int) -> str:
    b = _c(f"↓{behind}", 33) if behind > 0 else _c(f"↓{behind}", 2)
    a = _c(f"↑{ahead}", 32) if ahead > 0 else _c(f"↑{ahead}", 2)
    return f"{b} {a}"


def _github_tree_url(org_repo: str, branch: str) -> str:
    return f"https://github.com/{org_repo}/tree/{branch}"


def _github_commit_url(org_repo: str, full_hash: str) -> str:
    return f"https://github.com/{org_repo}/commit/{full_hash}"


def _get_pr_info(org_repo: str, branch: str) -> tuple[int, str] | None:
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", org_repo, "--head", branch,
             "--json", "number,url", "--limit", "1"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode != 0:
            return None
        data = json.loads(result.stdout)
        if not data:
            return None
        pr = data[0]
        return (pr["number"], pr["url"])
    except Exception:
        return None


def _link(url: str | None, text: str) -> str:
    return _osc8(url, text) if url else text


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_apply(config: Config, name: str | None = None) -> None:
    bare_repos_dir = config.root_dir / ".bare-git-repos"
    workspaces = config.workspaces
    if name:
        workspaces = [ws for ws in workspaces if ws.name == name]

    for ws in workspaces:
        ws_dir = config.root_dir / "workspaces" / ws.name

        # 1. Ensure bare repos + refs (parallel, max 2)
        resolved_specs: dict[str, BranchSpec] = {}

        def make_setup_task(alias, spec):
            def task():
                alias_remotes = config.remotes.get(alias, {})
                bare_repo = bare_repos_dir / f"{alias}.git"
                ensure_bare_repo(alias, alias_remotes, bare_repos_dir)
                resolved_specs[alias] = resolve_spec(bare_repo, spec, alias_remotes)
            return task

        tasks = [make_setup_task(alias, spec) for alias, spec in ws.repos.items()]
        parallel_fetch(tasks, max_workers=2)

        # 2. Create worktrees if they don't exist
        for alias, resolved in resolved_specs.items():
            bare_repo = bare_repos_dir / f"{alias}.git"
            worktree_path = ws_dir / alias
            if not worktree_exists(bare_repo, worktree_path):
                subprocess.run(["git", "-C", str(bare_repo), "worktree", "prune"], check=True)
                ws_dir.mkdir(parents=True, exist_ok=True)
                create_worktree(bare_repo, worktree_path, resolved)

        # 3. Write all workspace files (always overwrite)
        ws_dir.mkdir(parents=True, exist_ok=True)
        (ws_dir / "odoorc").write_text(make_odoorc(ws, config))
        (ws_dir / "odools.toml").write_text(make_odools_toml(ws))
        (ws_dir / "mise.toml").write_text(make_mise_toml())
        (ws_dir / "requirements-dev.txt").write_text(make_requirements_dev())

        vscode_dir = ws_dir / ".vscode"
        vscode_dir.mkdir(exist_ok=True)
        (vscode_dir / "settings.json").write_text(make_vscode_settings(ws))
        (vscode_dir / "launch.json").write_text(make_vscode_launch())

        zed_dir = ws_dir / ".zed"
        zed_dir.mkdir(exist_ok=True)
        (zed_dir / "settings.json").write_text(make_zed_settings(ws))
        (zed_dir / "debug.json").write_text(make_zed_debug())

        (ws_dir / "pyrightconfig.json").write_text(make_pyrightconfig())

        # 4. Trust the generated mise file
        subprocess.run(["mise", "trust", str(ws_dir / "mise.toml")], check=True)


def cmd_remove(config: Config, name: str) -> None:
    workspaces = [ws for ws in config.workspaces if ws.name == name]
    if not workspaces:
        print(f"No workspace named '{name}'", file=sys.stderr)
        sys.exit(1)

    ws = workspaces[0]
    bare_repos_dir = config.root_dir / ".bare-git-repos"
    ws_dir = config.root_dir / "workspaces" / name

    for alias, spec in ws.repos.items():
        bare_repo = bare_repos_dir / f"{alias}.git"
        worktree_path = ws_dir / alias
        if worktree_path.exists():
            remove_worktree(bare_repo, worktree_path, spec.local_branch)

    if ws_dir.exists():
        rmtree(ws_dir)

    config_path = config.root_dir / "ow.toml"
    archive_workspace(config_path, ws)
    remaining = [w for w in config.workspaces if w.name != name]
    update_config_workspaces(config_path, remaining)


def cmd_status(config: Config, name: str | None = None) -> None:
    workspaces = config.workspaces
    if name:
        workspaces = [ws for ws in workspaces if ws.name == name]

    for ws in workspaces:
        ws_dir = config.root_dir / "workspaces" / ws.name
        print(_c(f"[{ws.name}]", 1, 36))
        print("    " + _c("branches", 2))

        first_attached_branch: str | None = None
        pr_links: list[tuple[str, int, str]] = []

        bare_repos_dir = config.root_dir / ".bare-git-repos"
        max_alias_len = max(len(a) for a in ws.repos)

        for alias, spec in ws.repos.items():
            padding = " " * (max_alias_len - len(alias) + 1)
            worktree_path = ws_dir / alias
            if not worktree_path.exists():
                print(f"        {alias}:{padding}{_c('(not applied)', 2)}")
                continue

            alias_remotes = config.remotes.get(alias, {})

            bare_repo = bare_repos_dir / f"{alias}.git"
            try:
                spec = resolve_spec_local(bare_repo, spec, alias_remotes)
            except (RuntimeError, subprocess.CalledProcessError):
                pass  # keep original spec; git error caught in the outer try/except

            # Helper: get org/repo for a given remote name
            def org_repo_for(remote_name: str) -> str | None:
                rc = alias_remotes.get(remote_name)
                return _parse_github_org_repo(rc.url) if rc else None

            try:
                if spec.is_detached:
                    ahead, behind = get_rev_list_count(worktree_path, "HEAD", spec.base_ref)
                    short_hash, full_hash = get_worktree_head(worktree_path)

                    base_org_repo = org_repo_for(spec.remote)
                    base_url = _github_tree_url(base_org_repo, spec.branch) if base_org_repo else None
                    commit_url = _github_commit_url(base_org_repo, full_hash) if base_org_repo else None

                    base_text = _link(base_url, _c(spec.base_ref, 1))
                    hash_text = _link(commit_url, _c(short_hash, 33))
                    status = f"{base_text} {_counts(behind, ahead)} ({_c('DETACHED', 33)}: {hash_text})"

                else:
                    if first_attached_branch is None:
                        first_attached_branch = spec.local_branch

                    upstream = get_upstream(worktree_path)
                    if upstream:
                        ahead_up, behind_up = get_rev_list_count(worktree_path, "HEAD", upstream)

                        up_parts = upstream.split("/", 1)
                        up_remote = up_parts[0] if len(up_parts) == 2 else "origin"
                        up_branch = up_parts[1] if len(up_parts) == 2 else upstream
                        up_org_repo = org_repo_for(up_remote)
                        up_url = _github_tree_url(up_org_repo, up_branch) if up_org_repo else None

                        if up_org_repo:
                            pr_info = _get_pr_info(up_org_repo, up_branch)
                            if pr_info:
                                pr_links.append((up_org_repo, pr_info[0], pr_info[1]))

                        if upstream != spec.base_ref:
                            # Case 1: upstream ≠ base — standard format
                            ahead_base, behind_base = get_rev_list_count(worktree_path, upstream, spec.base_ref)
                            base_org_repo = org_repo_for(spec.remote)
                            base_url = _github_tree_url(base_org_repo, spec.branch) if base_org_repo else None
                            display_text = _link(up_url, _c(upstream, 1))
                            base_text = _link(base_url, _c(spec.base_ref, 1))
                            status = f"{display_text} {_counts(behind_up, ahead_up)} ({base_text} {_counts(behind_base, ahead_base)})"
                        else:
                            # Case 2: upstream == base — show local branch as primary
                            upstream_text = _link(up_url, _c(upstream, 1))
                            status = f"{_c(spec.local_branch, 1)} {_c('(local)', 2)} ({upstream_text} {_counts(behind_up, ahead_up)})"

                    else:
                        # Case 3: no upstream
                        base_org_repo = org_repo_for(spec.remote)
                        base_url = _github_tree_url(base_org_repo, spec.branch) if base_org_repo else None
                        ahead_base, behind_base = get_rev_list_count(worktree_path, "HEAD", spec.base_ref)
                        base_text = _link(base_url, _c(spec.base_ref, 1))
                        status = f"{_c(spec.local_branch, 1)} {_c('(local)', 2)} ({base_text} {_counts(behind_base, ahead_base)})"

            except subprocess.CalledProcessError:
                status = _c("(error)", 31)

            print(f"        {alias}:{padding}{status}")

        print("    " + _c("links", 2))
        for org_repo, pr_num, pr_url in pr_links:
            pr_text = _osc8(pr_url, f"{org_repo}#{pr_num}")
            print(f"        pr:     {pr_text}")

        if first_attached_branch:
            runbot_url = f"https://runbot.odoo.com/runbot/bundle/{first_attached_branch}"
            runbot_text = _osc8(runbot_url, first_attached_branch)
            print(f"        runbot: {runbot_text}")

        print()


def cmd_create(config: Config, name: str, repo_specs: list[str]) -> None:
    repos = {}
    for spec_str in repo_specs:
        alias, spec = spec_str.split(":", 1)
        repos[alias] = parse_branch_spec(spec)

    ws = WorkspaceConfig(name=name, repos=repos)
    config.workspaces.append(ws)

    config_path = config.root_dir / "ow.toml"
    with open(config_path, "a") as f:
        f.write("\n" + format_workspace(ws))

    cmd_apply(config, name=name)


def cmd_rebase(config: Config, name: str) -> None:
    bare_repos_dir = config.root_dir / ".bare-git-repos"
    workspaces = [ws for ws in config.workspaces if ws.name == name]
    if not workspaces:
        print(f"No workspace named '{name}'", file=sys.stderr)
        sys.exit(1)

    for ws in workspaces:
        ws_dir = config.root_dir / "workspaces" / ws.name

        # Parallel: resolve remote and fetch latest
        resolved_specs: dict[str, BranchSpec] = {}

        def make_fetch_task(alias, spec):
            def task():
                alias_remotes = config.remotes.get(alias, {})
                bare_repo = bare_repos_dir / f"{alias}.git"
                resolved = resolve_spec(bare_repo, spec, alias_remotes)
                resolved_specs[alias] = resolved
                subprocess.run(
                    ["git", "-C", str(bare_repo), "fetch", resolved.remote,
                     f"{resolved.branch}:refs/remotes/{resolved.remote}/{resolved.branch}"],
                    check=True,
                )
            return task

        fetch_tasks = [make_fetch_task(alias, spec) for alias, spec in ws.repos.items()]
        parallel_fetch(fetch_tasks, max_workers=2)

        # Sequential rebases
        for alias, resolved in resolved_specs.items():
            worktree_path = ws_dir / alias
            if not worktree_path.exists():
                continue
            if resolved.is_detached:
                subprocess.run(
                    ["git", "-C", str(worktree_path), "switch", "--detach", resolved.base_ref],
                    check=True,
                )
            else:
                subprocess.run(
                    ["git", "-C", str(worktree_path), "rebase", resolved.base_ref],
                    check=True,
                )
